### ISSUE TITLE
The library causes an exception when using a synchronous call

### ISSUE THREAD

**Issue by sboo** [pthomain/dejavu#48]
I'm calling my API in the context of a Worker.  Since this runs in the background already,  instead of using a `Single<T>`,  the API method returns a `Call<T>`.

This in turn causes the following error:
```
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type retrofit2.CallAdapter<kotlin.Any, kotlin.Any>
        at dev.pthomain.android.dejavu.retrofit.RetrofitCallAdapterFactory.get(RetrofitCallAdapterFactory.kt:112)
        at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:243)
        at retrofit2.Retrofit.callAdapter(Retrofit.java:227)
        at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:103)
        at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:66) 
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:37) 
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:192) 
        at retrofit2.Retrofit$1.invoke(Retrofit.java:149) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
        at $Proxy2.updateField(Unknown Source) 
```

I'm using `com.github.pthomain:dejavu:2.0.0-beta13`

If you need any more context or have a tip how I can solve this, let me know.

**Comment by sboo** [comment]
I'm using an RxWorker now, but still curious where the exception comes from when using `Call<T>`

**Comment by pthomain** [comment]
Hi @sboo, thanks for reporting this bug. 
It seems the issue might be that you are trying to use the call adapter factory for a call that does not return a RxJava type, e.g. returning `Call<T>` instead of `Observable<T>` for instance. 
This library only supports RxJava call adapters and there is no current fallback for default Retrofit return types.
You should be able to fix this by changing your call definition to return an `Observable<T>` or `Single<T>`. You can still choose to make the call synchronously by using the proper RxJava schedulers.

Hope that helps :)

Pierre

**Comment by pthomain** [comment]
The exception comes from the original `RxJava2CallAdapterFactory` as provided by Retrofit:

```java
   Class<?> rawType = getRawType(returnType);

    if (rawType == Completable.class) {
      // Completable is not parameterized (which is what the rest of this method deals with) so it
      // can only be created with a single configuration.
      return new RxJava2CallAdapter(Void.class, scheduler, isAsync, false, true, false, false,
          false, true);
    }

    boolean isFlowable = rawType == Flowable.class;
    boolean isSingle = rawType == Single.class;
    boolean isMaybe = rawType == Maybe.class;
    if (rawType != Observable.class && !isFlowable && !isSingle && !isMaybe) {
      return null;
    }
```
